name: Catalog CI Workflow

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'services/catalog/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'services/catalog/**'

concurrency:
  group: ${{github.workflow}}-${{ github.ref }}
  cancel-in-progress: true

env:
  DOTNET_VERSION: '9.0.x'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build and Test .NET Service
    defaults:
      run:
        working-directory: services/catalog

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          cache: true
          cache-dependency-path: ./**/*.csproj

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: |
          dotnet build --no-restore --configuration Release --verbosity minimal

      - name: Test
        run: |
          dotnet test --no-restore --no-build --configuration Release --verbosity normal
  
  dependency-check:
    runs-on: ubuntu-latest
    name: Dependency Check
    permissions:
      contents: read
      pull-requests: write
    defaults:
      run:
        working-directory: services/catalog
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          comment-summary-in-pr: true